import { useLanguage } from "./languageContext"
const thai: Record<string, string> = {
  "Finances": "การเงิน",
  "People": "ทีมและบุคลากร",
  "Projects": "โครงการและลูกค้า",
  "Accounting & actions": "บัญชีและงานที่ต้องทำ",
  "Investor dossier": "สรุปสำหรับนักลงทุน",
  "Cash on hand": "เงินสดคงเหลือ",
  "Founding capital": "เงินทุนเริ่มต้น",
  "Monthly burn": "รายจ่ายต่อเดือน",
  "Recurring OpEx": "รายจ่ายประจำ",
  "Outstanding AR": "ลูกหนี้คงค้าง",
  "Expense ledger": "บัญชีรายจ่าย",
  "Action queue": "งานที่ต้องทำ",
  "Monthly people cost": "ค่าใช้จ่ายทีมต่อเดือน",
  "AI operators": "ผู้ช่วย AI",
  "Human staff": "พนักงาน",
  "Avg AI efficiency": "ประสิทธิภาพ AI เฉลี่ย",
  "Contracted revenue": "รายได้ตามสัญญา",
  "Runway": "ระยะเวลาที่เงินพอใช้",
  "At current burn": "ตามรายจ่ายปัจจุบัน",
  "Spend allocation": "สัดส่วนรายจ่าย",
  "Projects in flight": "โครงการที่กำลังดำเนินการ",
  "Credit & installments": "สินเชื่อและเงินผ่อน",
  "Revenue pipeline": "โอกาสรายได้",
  "Received to date": "รับเงินแล้ว",
  "Contracted": "ตามสัญญา",
  "Outstanding": "ยอดคงค้าง",
  "Expected pipeline": "โอกาสรายได้ถ่วงน้ำหนัก",
  "Spend allocation this month": "สัดส่วนรายจ่ายเดือนนี้",
  "Runway projection": "ประมาณการเงินสด",
  "Benchmarks": "ค่าประกอบการเทียบ",
  "Objectives & key results": "เป้าหมายและผลลัพธ์",
  "What must happen next": "งานที่ต้องจัดการต่อ",
  "Invoices & receivables": "ใบแจ้งหนี้และลูกหนี้",
  "People OpEx split": "สัดส่วนค่าใช้จ่ายทีม",
  "Register your company": "ข้อมูลบริษัท",
  "Finish setup": "เสร็จสิ้นการตั้งค่า",
  "Recorded capital": "เงินทุนที่บันทึกแล้ว",
  "Add expense": "เพิ่มรายจ่าย",
  "Add AI operator": "เพิ่มผู้ช่วย AI",
  "Add human employee": "เพิ่มพนักงาน",
  "New project": "สร้างโครงการ",
  "Add loan / credit line": "เพิ่มสินเชื่อ",
  "Cancel": "ยกเลิก",
  "Close": "ปิด",
  "Add": "เพิ่ม",
  "Create": "สร้าง",
  "Record": "บันทึก",
  "Remove": "ลบ",
  "Continue": "ถัดไป",
  "Back": "ย้อนกลับ",
  "Print dossier": "พิมพ์สรุป",
  "+ Add expense": "+ เพิ่มรายจ่าย",
  "+ Add operator": "+ เพิ่มผู้ช่วย AI",
  "+ Add employee": "+ เพิ่มพนักงาน",
  "+ New project": "+ สร้างโครงการ",
  "+ Add loan": "+ เพิ่มสินเชื่อ",
  "+ Upload file": "+ เพิ่มชื่อไฟล์",
  "Move to Backlog": "ย้ายไปงานรอเริ่ม",
  "Mark paid": "บันทึกรับเงินครบ",
  "Name": "ชื่อ",
  "Role": "ตำแหน่ง",
  "Type": "ประเภท",
  "Started": "วันที่เริ่ม",
  "Salary / mo": "เงินเดือน",
  "Monthly salary": "เงินเดือน",
  "Monthly cost": "ค่าใช้จ่ายต่อเดือน",
  "Efficiency": "ประสิทธิภาพ",
  "Efficiency %": "ประสิทธิภาพ %",
  "Vendor": "ผู้ขาย",
  "Date": "วันที่",
  "Category": "หมวดหมู่",
  "Owner": "ผู้รับผิดชอบ",
  "Project": "โครงการ",
  "Client": "ลูกค้า",
  "Tasks": "งาน",
  "Status": "สถานะ",
  "Action": "การจัดการ",
  "Amount": "จำนวนเงิน",
  "Title": "ชื่อโครงการ",
  "Checklist": "รายการงาน",
  "Files": "ไฟล์",
  "Notes": "บันทึก",
  "Source": "แหล่งที่มา",
  "Tax ID": "เลขประจำตัวผู้เสียภาษี",
  "Capital amount": "จำนวนเงินทุน",
  "Company name": "ชื่อบริษัท",
  "Registration number": "เลขทะเบียนบริษัท",
  "Legal name": "ชื่อบริษัทตามทะเบียน",
  "Country": "ประเทศ",
  "Industry": "ประเภทธุรกิจ",
  "Founded": "วันที่ก่อตั้ง",
  "Registered address": "ที่อยู่ตามทะเบียน",
  "Lender": "ผู้ให้กู้",
  "Principal": "เงินต้น",
  "Rate": "ดอกเบี้ย",
  "Term": "ระยะเวลา",
  "Installment": "เงินผ่อน",
  "Annual rate (%)": "ดอกเบี้ยต่อปี (%)",
  "Term (months)": "ระยะเวลา (เดือน)",
  "Runway at current burn": "ระยะเวลาที่เงินพอใช้ตามรายจ่ายปัจจุบัน",
  "Now": "ปัจจุบัน",
  "Cash hits zero": "เงินสดหมด",
  "Objective": "เป้าหมาย",
  "Operator reads": "ข้อสังเกตจากข้อมูล",
  "Operator read": "ข้อสังเกตจากข้อมูล",
  "AI read": "คำแนะนำตามกฎ",
  "Human": "พนักงาน",
  "No notes yet.": "ยังไม่มีบันทึก",
  "No files.": "ยังไม่มีชื่อไฟล์",
  "No human employees yet.": "ยังไม่มีพนักงาน",
  "No outstanding invoices.": "ไม่มีใบแจ้งหนี้คงค้าง",
  "Queue clear.": "ไม่มีงานค้าง",
  "No capital recorded yet.": "ยังไม่มีเงินทุนที่บันทึก",
  "No expenses yet. Connect Gmail or add manually.": "ยังไม่มีรายจ่าย เพิ่มเองหรือใช้เพิ่มเอกสาร",
  "Record expenses to see the projection.": "บันทึกรายจ่ายเพื่อดูประมาณการ",
  "Drag cards between columns.": "ลากการ์ดเพื่อย้ายสถานะ หรือเปิดการ์ดแล้วเลือกสถานะ",
  "Add a task": "เพิ่มงาน",
  "Log a note": "เพิ่มบันทึก",
  "Backlog": "งานรอเริ่ม",
  "In progress": "กำลังทำ",
  "Review": "รอตรวจ",
  "Done": "เสร็จแล้ว",
  "Feeds ERP OpEx directly": "รวมในรายจ่าย ERP",
  "Self-reported / rated": "คะแนนที่ผู้ใช้ประเมิน",
  "Reflects into ERP monthly burn": "รวมในรายจ่ายต่อเดือนของ ERP",
  "Derived + manual": "รายการจากข้อมูลและรายการที่เพิ่มเอง",
  "Cash in": "เงินสดที่รับแล้ว",
  "Contracted, unbilled": "ยอดสัญญาที่ยังไม่ได้รับ",
  "Tier-weighted": "ถ่วงน้ำหนักตามระดับโอกาส",
  "No burn": "ไม่มีรายจ่าย",
  "CapEx vs OpEx": "รายจ่ายลงทุนเทียบรายจ่ายดำเนินงาน",
  "You vs seed-stage median": "ค่าตัวอย่างเทียบสตาร์ทอัประยะแรก",
  "Transparent — all members": "รายการรายจ่ายในพื้นที่ทำงานนี้",
  "Commissioned deals · tax-ready": "โครงการที่ตกลงแล้ว",
  "Put in a little. The system finds the rest.": "กรอกข้อมูลบริษัทที่ตรวจสอบแล้ว",
  "Enter verified company details. Lookup is a sample registry.": "กรอกข้อมูลบริษัทที่ตรวจสอบแล้ว การค้นหาใช้ทะเบียนตัวอย่าง",
  "Enter paid-in funds. Registered capital is not always paid-in capital.": "กรอกเงินทุนที่จ่ายจริง ทุนจดทะเบียนอาจไม่ใช่เงินที่ได้รับจริง",
  "Your workspace starts with the entries you approved.": "พื้นที่ทำงานเริ่มจากรายการที่คุณอนุมัติ",
  "Preview sample registry": "ดูทะเบียนตัวอย่าง",
  "Preview sample extraction": "ดูตัวอย่างการอ่านเอกสาร",
  "Example only. Upload actual PDFs from Add document after setup.": "ตัวอย่างเท่านั้น อัปโหลด PDF จริงจากเพิ่มเอกสารหลังตั้งค่า",
  "or enter manually": "หรือกรอกเอง",
  "Add entry": "เพิ่มรายการ",
  "Connect your business inbox": "เชื่อมต่อกล่องจดหมายบริษัท",
  "Import receipts through Add document, review AI proposals, then approve.": "นำเข้าใบเสร็จผ่านเพิ่มเอกสาร ตรวจข้อเสนอของ AI แล้วอนุมัติ",
  "Gmail is not connected. No receipts will be imported.": "ยังไม่เชื่อมต่อ Gmail จึงไม่มีการนำเข้าใบเสร็จ",
  "Sign in": "เข้าสู่ระบบ",
  "Sign in to the database": "เข้าสู่ระบบฐานข้อมูล",
  "Loading Google sign-in…": "กำลังโหลดการเข้าสู่ระบบ Google…",
  "Connect to Google Sheet": "เชื่อมต่อ Google Sheets",
  "Sheet Web App URL": "URL ของ Apps Script",
  "Apps Script": "Apps Script",
  "Setup — three steps": "ตั้งค่า 3 ขั้นตอน",
  "Create a fresh Sheet": "สร้าง Google Sheets ใหม่",
  "Install the script": "ติดตั้งสคริปต์",
  "Deploy as Web App": "เผยแพร่เป็น Web App",
  "Security Notice": "ข้อมูลที่จะส่ง",
  "Sheets is the engine. EACH is the lens.": "Google Sheets เป็นสำเนาที่แก้ไขได้",
  "Pull from Sheet": "ดึงข้อมูลมาตรวจ",
  "Disconnect": "ตัดการเชื่อมต่อ",
  "Test & Connect": "ทดสอบและเชื่อมต่อ",
  "Copy full script": "คัดลอกสคริปต์ทั้งหมด",
  "I understand": "ฉันเข้าใจ",
  "uploaded": "บันทึกชื่อแล้ว"
}
export function useCopy() { const { language } = useLanguage(); return (text: string) => language === "th" ? thai[text] || text : text }
